### ISSUE TITLE
Items in sidedrawer don't get highlighted during navigation

### ISSUE THREAD

**Issue by manikjain** [NativeScript/template-drawer-navigation-ng#106]
PR here: https://github.com/NativeScript/template-drawer-navigation-ng/pull/105

While navigating to different places in the side drawer, the items in the side drawer don't get highlighted and only the Home component remains highlighted.

This is because after `this._selectedPage` is initialised in `ngOnInit` method, it is never reset after a user taps on a sidedrawer item.

Test:

I navigated to the search component as seen below:

![image](https://user-images.githubusercontent.com/21245503/40295233-44b3e3b4-5cf6-11e8-8649-ba9301125cbe.png)

However, the home component still shows highlighted:

![image](https://user-images.githubusercontent.com/21245503/40295290-67451ef2-5cf6-11e8-9113-32bf2c6edd46.png)

After resetting _selectedPage in the `onNavItemTap` method, the items in side drawer get highlighted:

![image](https://user-images.githubusercontent.com/21245503/40295522-33635ee0-5cf7-11e8-87f2-2420645cd3a2.png)

**Comment by manoldonev** [comment]
Already fixed with #102
