### ISSUE TITLE
How to disable drawer on specific pages.

### ISSUE THREAD

**Issue by JijeshP** [NativeScript/template-drawer-navigation-ng#108]
How can i disable drawers on specific pages like login ?

**Comment by shamoh19** [comment]
+1

**Comment by yonkoGH** [comment]
- first of all hide the slide drawer button
- second disable the swipe gesture to open menu using this code inside your page component class

    ngAfterViewInit(): void {
        this._drawer = this.drawerComponent.sideDrawer;
        if (this._drawer.ios) {
            //for ios
            this._drawer.ios.defaultSideDrawer.allowEdgeSwipe = false;
        }
    }
    //call when slide drawer loaded
    public onSideDrawerLoaded(): void {
        if (isAndroid) {
            //for android
            this._drawer.android.setTouchTargetThreshold(0);
        }
    }

**Comment by davorpeic** [comment]
If you are using new root method, you can remove buttons that open drawer as @yonkoGH said, and then you would simple remove gestures like this

```javascript
import { RadSideDrawer } from "nativescript-ui-sidedrawer";

constructor (){
    let sideDrawer = <RadSideDrawer>app.getRootView();
    sideDrawer.gesturesEnabled = false;
}
```

**Comment by JijeshP** [comment]
Thanks @yonkoGH @davorpeic

**Comment by manoldonev** [comment]
Another approach would be to use a modal dialog for your login screen (if that makes sense for your scenario), then you would not need to disable the drawer on your main content.

**Comment by davorpeic** [comment]
The issue we found with disabling `gestureEnabled` with new root based drawer is that gestures on this elements get disabled "per entire app" and as we have several root pages, we want to leave gestures enabled, so we are playing with router paths to identify where gestures should be disabled and where not.
