### ISSUE TITLE
Can't create Login page

### ISSUE THREAD

**Issue by xsterlas** [NativeScript/template-drawer-navigation-ng#111]
With this update all the pages are loaded inside the sidedrawer. 
If you want to create a Login page that don't have the sidedrawer is not possible.
I tried to hidden the sidedrawer but any option works.
Can you give me a solution please?

**Comment by NickIliev** [comment]
@xsterlas you can use `RadSideDrawer` as toot (just as done in the template) and navigate yo login page.
Then  in the login page, you could explicitly hide and disable the drawer as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/login/login.component.ts#L44-L45)

```
this.drawer = <RadSideDrawer>getRootView();
this.drawer.gesturesEnabled = false;
```

**Comment by xsterlas** [comment]
Thank you Nick,

I don’t know what I was doing wrong because I tried with gesturesEnabled in false. But sure I did something wrong because now is working.

But I need some more help because with the last template I could change the menu depending of the kind of user was login in.

Now I don’t know how to do it because the menu is defined before the login.

Can you give me some solution please?

Thank you so much


Salutacions,

Xavier Sanmarini
Software

[http://www.terlas.com/images/terlas_mail_logo.png]973 710 420 | www.terlas.com<http://www.terlas.com/> | xsanmarini@terlas.com<mailto:xsanmarini@terlas.com> | Disclaimer<https://www.terlas.com/disclaimer>

De: Nick Iliev [mailto:notifications@github.com]
Enviado el: lunes, 09 de julio de 2018 13:30
Para: NativeScript/template-drawer-navigation-ng <template-drawer-navigation-ng@noreply.github.com>
CC: Xavier Sanmarini <xsanmarini@terlas.net>; Mention <mention@noreply.github.com>
Asunto: Re: [NativeScript/template-drawer-navigation-ng] Can't create Login page (#111)


@xsterlas<https://github.com/xsterlas> you can use RadSideDrawer as toot (just as done in the template) and navigate yo login page.
Then in the login page, you could explicitly hide and disable the drawer as done here<https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/login/login.component.ts#L44-L45>

this.drawer = <RadSideDrawer>getRootView();

this.drawer.gesturesEnabled = false;
