### ISSUE TITLE
App hangs on iOS after navigating to "browse"

### ISSUE THREAD

**Issue by rdlauer** [NativeScript/template-drawer-navigation-ng#16]
As stated in the title. Using the app on the iOS Simulator, if you navigate to the "browse" menu option, you can no longer access the drawer. Android seems to work fine.

**Comment by DimitarTodorov** [comment]
Hi, Rob.
This is a known issue in the Progress UI for NativeScript Drawer component. We have already addressed it and a fix will be available in the next version of the Progress UI for NativeScript.

However, you should know that these repositories are public but they are still under “Work in progress” phase. You can explore them but there may be some issues in the samples.

Regards,
Dimitar.
