### ISSUE TITLE
Drawer does not open

### ISSUE THREAD

**Issue by jonnysamps** [NativeScript/template-drawer-navigation-ng#38]
**Problem**
The drawer opens just fine when on the `Home` page.  After navigating to any other screen the drawer no longer opens.

**Steps to reproduce**
1. Create a new project using this template with Nativescript Sidekick.
2. Run the project on an iOS simulator
3. Tap the drawer hamburger icon and see that the drawer opens 
4. Tap `Browse`. See that navigation occurs
5. Tap drawer hamburger icon. See that drawer does not open.

**Comment by lini** [comment]
Thank you for the information. This issue coming from the [Progress NativeScript UI](https://github.com/telerik/nativescript-ui-feedback) SideDrawer component. We will report it to the team and hope that a fix will be available in their next release

**Comment by simonettoa** [comment]
@jonnysamps  hi, right now I did a workaround in every page adding a function on NgInit:

`	

    ngOnInit(): void {
		...
		
        setTimeout(()=> {
            this.onDrawerRefresh();
        }, 100);
    }
    
    onDrawerRefresh(): void {
        this.drawerComponent.sideDrawer.closeDrawer();
    }`

**Comment by jonnysamps** [comment]
@simonettoa Thanks for the tip. I guess this implies that the sidedrawer is a shared component that gets re-used... and it's state doesn't get set properly on navigation.

**Comment by MilosStanic** [comment]
Just wanted to confirm the bug on iOS. Will try the workaround proposed by @simonettoa 
Also wanted to add, that even though the tap on hamburger icon doesn't work, but the drawer opens when you slide left-right from the left edge of the screen.
