### ISSUE TITLE
I cant create new project based on this template on my Mac

### ISSUE THREAD

**Issue by cmargulhano** [NativeScript/template-drawer-navigation-ng#43]
I try this command:

tns create HelloWorld --template https://github.com/NativeScript/template-drawer-navigation-ng --log trace

- Stack Track:

Loading extensions.
execFile: /Users/claudio/Library/Android/sdk/platform-tools/adb "help"
Exec uname -a 
 stdout: Darwin koradi-apple 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
 
 stderr: 
Exec npm -v 
 stdout: 5.4.0
 
 stderr: 
spawn: java "-version"
Exec node-gyp -v 
 stdout:  
 stderr: /bin/sh: node-gyp: command not found

Exec xcodebuild -version 
 stdout: Xcode 8.3.3
Build version 8E3004b
 
 stderr: 
Exec gem which xcodeproj 
 stdout: /Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj.rb
 
 stderr: 
Exec pod --version 
 stdout: 1.3.1
 
 stderr: 
Exec '/Users/claudio/Library/Android/sdk/platform-tools/adb' version 
 stdout: Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
Installed as /Users/claudio/Library/Android/sdk/platform-tools/adb
 
 stderr: 
spawn: /Users/claudio/Library/Android/sdk/emulator/emulator "-help"
Result when throw error is false:
{ stdout: 'Android Emulator usage: emulator [options] [-qemu args]\n  options:\n    -list-avds                     list available AVDs\n    -sysdir <dir>                  search for system disk images in <dir>\n    -system <file>                 read initial system image from <file>\n    -vendor <file>                 read initial vendor image from <file>\n    -writable-system               make system & vendor image writable after \'adb remount\'\n    -datadir <dir>                 write user data into <dir>\n    -kernel <file>                 use specific emulated kernel\n    -ramdisk <file>                ramdisk image (default <system>/ramdisk.img\n    -image <file>                  obsolete, use -system <file> instead\n    -initdata <file>               same as \'-init-data <file>\'\n    -data <file>                   data image (default <datadir>/userdata-qemu.img\n    -logcat-output <file>          output file of logcat(default none)\n    -partition-size <size>         system/data partition size in MBs\n    -cache <file>                  cache partition image (default is temporary file)\n    -cache-size <size>             cache partition size in MBs\n    -no-cache                      disable the cache partition\n    -nocache                       same as -no-cache\n    -sdcard <file>                 SD card image (default <datadir>/sdcard.img\n    -snapstorage <file>            file that contains all state snapshots (default <datadir>/snapshots.img)\n    -no-snapstorage                do not mount a snapshot storage file (this disables all snapshot functionality)\n    -snapshot <name>               name of snapshot within storage file for auto-start and auto-save (default \'default-boot\')\n    -no-snapshot                   perform a full boot and do not auto-save, but qemu vmload and vmsave operate on snapstorage\n    -no-snapshot-save              do not auto-save to snapshot on exit: abandon changed state\n    -no-snapshot-load              do not auto-start from snapshot: perform a full boot\n    -snapshot-list                 show a list of available snapshots\n    -no-snapshot-update-time       do not do try to correct snapshot time on restore\n    -wipe-data                     reset the user data image (copy it from initdata)\n    -avd <name>                    use a specific android virtual device\n    -skindir <dir>                 search skins in <dir> (default <system>/skins)\n    -skin <name>                   select a given skin\n    -no-skin                       deprecated: create an AVD with no skin instead\n    -noskin                        same as -no-skin\n    -memory <size>                 physical RAM size in MBs\n    -cores <number>                Set number of CPU cores to emulator\n    -accel <mode>                  Configure emulation acceleration\n    -no-accel                      Same as \'-accel off\'\n    -ranchu                        Use new emulator backend instead of the classic one\n    -engine <engine>               Select engine. auto|classic|qemu2\n    -netspeed <speed>              maximum network download/upload speeds\n    -netdelay <delay>              network latency emulation\n    -netfast                       disable network shaping\n    -code-profile <name>           enable code profiling\n    -show-kernel                   display kernel messages\n    -shell                         enable root shell on current terminal\n    -no-jni                        disable JNI checks in the Dalvik runtime\n    -nojni                         same as -no-jni\n    -logcat <tags>                 enable logcat output with given tags\n    -no-audio                      disable audio support\n    -noaudio                       same as -no-audio\n    -audio <backend>               use specific audio backend\n    -radio <device>                redirect radio modem interface to character device\n    -port <port>                   TCP port that will be used for the console\n    -ports <consoleport>,<adbport> TCP ports used for the console and adb bridge\n    -onion <image>                 use overlay PNG image over screen\n    -onion-alpha <%age>            specify onion-skin translucency\n    -onion-rotation 0|1|2|3        specify onion-skin rotation\n    -dpi-device <dpi>              specify device\'s resolution in dpi (default 165)\n    -scale <scale>                 scale emulator window (deprecated)\n    -http-proxy <proxy>            make TCP connections through a HTTP/HTTPS proxy\n    -timezone <timezone>           use this timezone instead of the host\'s default\n    -dns-server <servers>          use this DNS server(s) in the emulated system\n    -cpu-delay <cpudelay>          throttle CPU emulation\n    -no-boot-anim                  disable animation for faster boot\n    -no-window                     disable graphical window display\n    -version                       display emulator version number\n    -report-console <socket>       report console port to remote socket\n    -gps <device>                  redirect NMEA GPS to character device\n    -shell-serial <device>         specific character device for root shell\n    -tcpdump <file>                capture network packets to file\n    -bootchart <timeout>           enable bootcharting\n    -charmap <file>                use specific key character map\n    -studio-params <file>          used by Android Studio to provide parameters\n    -prop <name>=<value>           set system property on boot\n    -shared-net-id <number>        join the shared network, using IP address 10.1.2.<number>\n    -nand-limits <nlimits>         enforce NAND/Flash read/write thresholds\n    -gpu <mode>                    set hardware OpenGLES emulation mode\n    -camera-back <mode>            set emulation mode for a camera facing back\n    -camera-front <mode>           set emulation mode for a camera facing front\n    -webcam-list                   lists web cameras available for emulation\n    -screen <mode>                 set emulated screen mode\n    -force-32bit                   always use 32-bit emulator\n    -selinux <disabled|permissive> Set SELinux to either disabled or permissive mode\n    -unix-pipe <path>              Add <path> to the list of allowed Unix pipes\n    -fixed-scale                   Use fixed 1:1 scale for the initial emulator window.\n    -wait-for-debugger             Pause on launch and wait for a debugger process to attach before resuming\n    -skip-adb-auth                 Skip adb authentication dialogue\n    -metrics-to-console            Enable usage metrics and print the messages to stdout\n    -metrics-to-file <file>        Enable usage metrics and write the messages into specified file\n\n     -qemu args...                 pass arguments to qemu\n     -qemu -h                      display qemu help\n\n     -verbose                      same as \'-debug-init\'\n     -debug <tags>                 enable/disable debug messages\n     -debug-<tag>                  enable specific debug messages\n     -debug-no-<tag>               disable specific debug messages\n\n     -help                         print this help\n     -help-<option>                print option-specific help\n\n     -help-disk-images             about disk images\n     -help-debug-tags              debug tags for -debug <tags>\n     -help-char-devices            character <device> specification\n     -help-environment             environment variables\n     -help-virtual-device          virtual device management\n     -help-sdk-images              about disk images when using the SDK\n     -help-build-images            about disk images when building Android\n     -help-all                     prints all help content\n\n',
  stderr: '',
  exitCode: 0 }
The result of checking is Android Emulator installed is:
- stdout: Android Emulator usage: emulator [options] [-qemu args]
  options:
    -list-avds                     list available AVDs
    -sysdir <dir>                  search for system disk images in <dir>
    -system <file>                 read initial system image from <file>
    -vendor <file>                 read initial vendor image from <file>
    -writable-system               make system & vendor image writable after 'adb remount'
    -datadir <dir>                 write user data into <dir>
    -kernel <file>                 use specific emulated kernel
    -ramdisk <file>                ramdisk image (default <system>/ramdisk.img
    -image <file>                  obsolete, use -system <file> instead
    -initdata <file>               same as '-init-data <file>'
    -data <file>                   data image (default <datadir>/userdata-qemu.img
    -logcat-output <file>          output file of logcat(default none)
    -partition-size <size>         system/data partition size in MBs
    -cache <file>                  cache partition image (default is temporary file)
    -cache-size <size>             cache partition size in MBs
    -no-cache                      disable the cache partition
    -nocache                       same as -no-cache
    -sdcard <file>                 SD card image (default <datadir>/sdcard.img
    -snapstorage <file>            file that contains all state snapshots (default <datadir>/snapshots.img)
    -no-snapstorage                do not mount a snapshot storage file (this disables all snapshot functionality)
    -snapshot <name>               name of snapshot within storage file for auto-start and auto-save (default 'default-boot')
    -no-snapshot                   perform a full boot and do not auto-save, but qemu vmload and vmsave operate on snapstorage
    -no-snapshot-save              do not auto-save to snapshot on exit: abandon changed state
    -no-snapshot-load              do not auto-start from snapshot: perform a full boot
    -snapshot-list                 show a list of available snapshots
    -no-snapshot-update-time       do not do try to correct snapshot time on restore
    -wipe-data                     reset the user data image (copy it from initdata)
    -avd <name>                    use a specific android virtual device
    -skindir <dir>                 search skins in <dir> (default <system>/skins)
    -skin <name>                   select a given skin
    -no-skin                       deprecated: create an AVD with no skin instead
    -noskin                        same as -no-skin
    -memory <size>                 physical RAM size in MBs
    -cores <number>                Set number of CPU cores to emulator
    -accel <mode>                  Configure emulation acceleration
    -no-accel                      Same as '-accel off'
    -ranchu                        Use new emulator backend instead of the classic one
    -engine <engine>               Select engine. auto|classic|qemu2
    -netspeed <speed>              maximum network download/upload speeds
    -netdelay <delay>              network latency emulation
    -netfast                       disable network shaping
    -code-profile <name>           enable code profiling
    -show-kernel                   display kernel messages
    -shell                         enable root shell on current terminal
    -no-jni                        disable JNI checks in the Dalvik runtime
    -nojni                         same as -no-jni
    -logcat <tags>                 enable logcat output with given tags
    -no-audio                      disable audio support
    -noaudio                       same as -no-audio
    -audio <backend>               use specific audio backend
    -radio <device>                redirect radio modem interface to character device
    -port <port>                   TCP port that will be used for the console
    -ports <consoleport>,<adbport> TCP ports used for the console and adb bridge
    -onion <image>                 use overlay PNG image over screen
    -onion-alpha <%age>            specify onion-skin translucency
    -onion-rotation 0|1|2|3        specify onion-skin rotation
    -dpi-device <dpi>              specify device's resolution in dpi (default 165)
    -scale <scale>                 scale emulator window (deprecated)
    -http-proxy <proxy>            make TCP connections through a HTTP/HTTPS proxy
    -timezone <timezone>           use this timezone instead of the host's default
    -dns-server <servers>          use this DNS server(s) in the emulated system
    -cpu-delay <cpudelay>          throttle CPU emulation
    -no-boot-anim                  disable animation for faster boot
    -no-window                     disable graphical window display
    -version                       display emulator version number
    -report-console <socket>       report console port to remote socket
    -gps <device>                  redirect NMEA GPS to character device
    -shell-serial <device>         specific character device for root shell
    -tcpdump <file>                capture network packets to file
    -bootchart <timeout>           enable bootcharting
    -charmap <file>                use specific key character map
    -studio-params <file>          used by Android Studio to provide parameters
    -prop <name>=<value>           set system property on boot
    -shared-net-id <number>        join the shared network, using IP address 10.1.2.<number>
    -nand-limits <nlimits>         enforce NAND/Flash read/write thresholds
    -gpu <mode>                    set hardware OpenGLES emulation mode
    -camera-back <mode>            set emulation mode for a camera facing back
    -camera-front <mode>           set emulation mode for a camera facing front
    -webcam-list                   lists web cameras available for emulation
    -screen <mode>                 set emulated screen mode
    -force-32bit                   always use 32-bit emulator
    -selinux <disabled|permissive> Set SELinux to either disabled or permissive mode
    -unix-pipe <path>              Add <path> to the list of allowed Unix pipes
    -fixed-scale                   Use fixed 1:1 scale for the initial emulator window.
    -wait-for-debugger             Pause on launch and wait for a debugger process to attach before resuming
    -skip-adb-auth                 Skip adb authentication dialogue
    -metrics-to-console            Enable usage metrics and print the messages to stdout
    -metrics-to-file <file>        Enable usage metrics and write the messages into specified file

     -qemu args...                 pass arguments to qemu
     -qemu -h                      display qemu help

     -verbose                      same as '-debug-init'
     -debug <tags>                 enable/disable debug messages
     -debug-<tag>                  enable specific debug messages
     -debug-no-<tag>               disable specific debug messages

     -help                         print this help
     -help-<option>                print option-specific help

     -help-disk-images             about disk images
     -help-debug-tags              debug tags for -debug <tags>
     -help-char-devices            character <device> specification
     -help-environment             environment variables
     -help-virtual-device          virtual device management
     -help-sdk-images              about disk images when using the SDK
     -help-build-images            about disk images when building Android
     -help-all                     prints all help content

- stderr: 
Exec mono --version 
 stdout:  
 stderr: /bin/sh: mono: command not found

Exec git --version 
 stdout: git version 2.11.0 (Apple Git-81)
 
 stderr: 
Exec gradle -v 
 stdout:  
 stderr: /bin/sh: gradle: command not found

Exec "/Library/Java/Home/bin/javac" -version 
 stdout:  
 stderr: javac 1.8.0_121

System information:
{ procInfo: 'nativescript/3.1.3',
  platform: 'darwin',
  os: 'Darwin koradi-apple 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64\n',
  shell: '/bin/bash',
  dotNetVer: null,
  procArch: 'x64',
  nodeVer: 'v8.3.0',
  npmVer: '5.4.0',
  javaVer: '1.8.0',
  nodeGypVer: null,
  xcodeVer: 'Xcode 8.3.3\nBuild version 8E3004b\n',
  xcodeprojGemLocation: '/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj.rb\n',
  itunesInstalled: true,
  cocoapodVer: '1.3.1',
  adbVer: 'Android Debug Bridge version 1.0.39',
  emulatorInstalled: true,
  monoVer: null,
  gitVer: '2.11.0 (Apple Git-81)',
  gradleVer: null,
  javacVersion: '1.8.0_121' }
Initializing analytics statuses.
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'create'.
AnalyticsInstallationID: 82be1042-11a2-4002-a564-dc37b372bbf7
monitor not started
monitor not started
monitor not started
monitor has started, connecting to http://5752dabccfc54c4ab82aea9626b7338e.monitor-eqatec.com/json.ashx
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'NodeJSVersion' with value '8_3_0'.
Waiting for analytics to send information. Will check in a 100ms.
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29900
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29800
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29700
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29600
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29500
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29400
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29300
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29200
Waiting for analytics to send information. Will check in a 100ms.
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29900
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29800
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29700
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29600
Creating a new NativeScript project with name HelloWorld and id org.nativescript.HelloWorld at location /Users/claudio/Koradi/Projects/Koradi/HelloWorld
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'Template used for project creation' with value 'https://github.com/NativeScript/template-drawer-navigation-ng'.
Waiting for analytics to send information. Will check in a 100ms.
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29900
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29800
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29700
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29600
Using NativeScript verified template: https://github.com/NativeScript/template-drawer-navigation-ng with version undefined.
Installing  https://github.com/NativeScript/template-drawer-navigation-ng
spawn: npm "install" "https://github.com/NativeScript/template-drawer-navigation-ng" "--silent" "--save-exact" "--save"
Progress NativeScript UI Free is licensed under the Telerik End User License Agreement for UI for NativeScript Free: http://www.telerik.com/purchase/license-agreement/ui-for-nativescript-free
Error: Command npm install https://github.com/NativeScript/template-drawer-navigation-ng --silent --save-exact --save failed with exit code 1
    at ChildProcess.childProcess.on (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:234:36)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Error: Command npm install https://github.com/NativeScript/template-drawer-navigation-ng --silent --save-exact --save failed with exit code 1
    at ChildProcess.childProcess.on (/usr/local/lib/node_modules/nativescript/lib/node-package-manager.js:234:36)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'CLI' with value 'help'.
Waiting for analytics to send information. Will check in a 100ms.
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29900
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29800
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29700
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29600
List of registered commands: /?, appstore, appstore|upload, autocomplete, autocomplete|disable, autocomplete|enable, autocomplete|status, build, build|android, build|ios, clean-app, clean-app|android, clean-app|ios, create, debug, debug|android, debug|ios, deploy, dev-generate-help, dev-generate-messages, dev-post-install, dev-preuninstall, dev-test, dev-test|android, dev-test|ios, device, devices, devices|android, devices|ios, device|android, device|get-file, device|ios, device|list-applications, device|list-files, device|log, device|put-file, device|run, device|stop, device|uninstall, doctor, error-reporting, extension, extension|install, extension|uninstall, help, info, init, install, platform, platform|add, platform|clean, platform|remove, platform|update, plugin, plugin|add, plugin|install, plugin|remove, plugin|update, post-install-cli, prepare, proxy, proxy|clear, proxy|set, publish, publish|ios, run, run|android, run|ios, test, test|android, test|init, test|ios, update, usage-reporting
Reading help for command 'create'. FileName is 'create.md'.
# create

┌────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                      │ Synopsis                                                                                                                                                                │
│ Create from default        │ $ tns create <App Name> [--path <Directory>] [--appid <App ID>]                                                                                                         │
│ JavaScript template        │                                                                                                                                                                         │
│ Create from default        │ $ tns create <App Name> --template typescript [--path <Directory>] [--appid <App ID>] OR $ tns create <App Name> --tsc [--path <Directory>] [--appid <App ID>] OR       │
│ TypeScript template        │ $ tns create <App Name> --template tsc [--path <Directory>] [--appid <App ID>]                                                                                          │
│ Create from default        │ $ tns create <App Name> --template angular [--path <Directory>] [--appid <App ID>] OR $ tns create <App Name> --template ng [--path <Directory>] [--appid <App ID>]    │
│ Angular template           │ [39m OR $ tns create <App Name> --ng [--path <Directory>] [--appid <App ID>]                                                                                            │
│ Copy from existing project │ $ tns create <App Name> [--path <Directory>] [--appid <App ID>]                                                                                                         │
│ Create from custom         │ $ tns create <App Name> [--path <Directory>] [--appid <App ID>] --template <Template>                                                                                   │
│ template                   │                                                                                                                                                                         │
└────────────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Creates a new project for native development with NativeScript.

### Options

    * --path - Specifies the directory where you want to create the project, if different from the current directory. The directory must be empty.
    * --appid - Sets the application identifier for your project.
    * --template - Specifies a valid npm package which you want to use to create your project. If --template is not set, the NativeScript CLI creates the project from the default JavaScript hello-world template.
    * --ng - Sets the template for your project to the Angular template.
    * --tsc - Sets the template for your project to the TypeScript template.

### Attributes

    * <App Name> is the name of project. The specified name must meet the requirements of all platforms that you want to target. For more information about the <App Name> requirements, run $ tns help create
    * <App ID> is the application identifier for your project. It must be a domain name in reverse and must meet the requirements of all platforms that you want to target. If not specified, the application identifier is set to org.nativescript.<App name> For more information about the <App ID> requirements, run $ tns help create

Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track exception with message 'Command npm install https://github.com/NativeScript/template-drawer-navigation-ng --silent --save-exact --save failed with exit code 1'.
monitor has stopped
AnalyticsInstallationID: 82be1042-11a2-4002-a564-dc37b372bbf7
monitor not started
monitor not started
monitor not started
monitor has started, connecting to http://35478fe7de68431399e96212540a3d5d.monitor-eqatec.com/json.ashx
Analytics statuses: 
{ TrackFeatureUsage: 0, TrackExceptions: 0 }
Trying to track feature 'NodeJSVersion' with value '8_3_0'.
Waiting for analytics to send information. Will check in a 100ms.
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29900
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29800
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29700
Statistics was sent successfully (xhr). Monitor stopped.
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29600
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29500
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29400
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29300
Waiting for analytics to send information. Will check in a 100ms.
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29900
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29800
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29700
Statistics was sent successfully (xhr).
Waiting for analytics to send information. Will check in a 100ms. Remaining time is: 29600

**Comment by manoldonev** [comment]
@cmargulhano seems the problem is related to the latest npm@5.4.0. I would suggest you to use npm@5.3.0 to execute the `tns create` command while we sort out the root cause of the issue.

**Comment by cmargulhano** [comment]
Thanks @manoldonev. I was able to solve this problem. I installed a new version of the Android SDK and everything is allright.
