### ISSUE TITLE
how to get data from the textfield in RadListView itemTemplate ?

### ISSUE THREAD

**Issue by paceair** [NativeScript/template-drawer-navigation-ng#57]
hi guys,

I could not solve the below question, and have google search, and try many different ways.

```
<lv:RadListView items="{{ data }}" > 
   <lv:RadListView.itemTemplate>  

            <StackLayout>
                <TextField text="{{ data1  }}" />  
                <TextField text="{{ data2 }}" />
            </StackLayout>         
    
    </lv:RadListView.itemTemplate>
 </lv:RadListView>

```
**Question**
If the user key in the above 10 different index TextFields of data1 and data2 in the itemTemplate, 
how to get the 10 different index TextFields of data1 and data2  ?

Appreciate anyone who could help to solve the above question. Thank you.

**Comment by MIYankov** [comment]
@paceair This is a general vanilla {N} question and this is the repo for a {N} template using Angular and a RadSideDrawer component. It's not quite the correct place to ask this. We noticed you posted this question on SO - https://stackoverflow.com/questions/46530394/how-to-get-data-from-the-textfield-in-radlistview-itemtemplate-nativescript . We will answer you there.

Additionally, a very good place to ask general how-to questions is the [NativeScript Forum](https://discourse.nativescript.org/).
