### ISSUE TITLE
onDrawerButtonTap works only on Home page

### ISSUE THREAD

**Issue by rugdealer** [NativeScript/template-drawer-navigation-ng#8]
Created the project and ran `tns run ios`, after navigating to another page, the Navigation Button is unresponsive. It does not throw any errors. Added a console.log on the method `onDrawerButtonTap` in the `search.component.ts`.

Using the Emulator: 
> iPhone SE - iOS 10.2 (14C89)

Adding this in `search.component.ts` will unbug the problem letting access back to the button. However, navigating to another menu item causes the bug to re-appear.

```
    ngOnInit(): void {
        console.log(`ngOnInit.`);
        setTimeout(()=>{
            this.onDrawerButtonTap();
            console.log(`Called button tap.`);
        }, 1000);
    }
```

**Comment by DimitarTodorov** [comment]
Hi, rugdealer!
This is a known issue in the Progress UI for NativeScript Drawer component. We have already addressed it and a fix will be available in the next version of the UI for NativeScript. 

However, you should know that these repositories are public but they are still under “Work in progress” phase. You can explore them but there may be some issues in the samples.

Regards,
Dimitar.
