### ISSUE TITLE
Unable to install this template

### ISSUE THREAD

**Issue by ehtishammalik** [NativeScript/template-drawer-navigation-ng#84]
npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /tmp/npm-3822-db5bd63f/registry.npmjs.org/node-gyp/-/node-gyp-3.6.2.tgz
npm ERR! Expected: 9bfbe54562286284838e750eac05295853fa1c60
npm ERR! Actual:   bb562b6bd60e663f99053c32d11bb21d31f8ed85
npm ERR! From:     https://registry.npmjs.org/node-gyp/-/node-gyp-3.6.2.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hamza/WS/my-app-name/npm-debug.log
Command npm install failed with exit code 1

**Comment by manoldonev** [comment]
Are you able to successfully install node-gyp on your machine at all? You can try `npm install -g node-gyp` and if successful, try installing the template again.

Note, however, that there are similar reports for this error e.g. [here](https://github.com/angular/angular-cli/issues/7549) so you might need to update to a more recent version of npm as well.
