### ISSUE TITLE
Unable to install this template 

### ISSUE THREAD

**Issue by pradt** [NativeScript/template-drawer-navigation-ng#85]
I'm getting the following when I run 

`npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/home/prad/.nvm/versions/node/v7.10.1/bin/node" "/home/prad/.nvm/versions/node/v7.10.1/bin/npm" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! path /home/prad/.npm/node-sass/4.7.2/package
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir

npm ERR! Error: EACCES: permission denied, mkdir '/home/prad/.npm/node-sass/4.7.2/package'
npm ERR!  { Error: EACCES: permission denied, mkdir '/home/prad/.npm/node-sass/4.7.2/package'
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/prad/.npm/node-sass/4.7.2/package',
npm ERR!   parent: 'nativescript-dev-sass' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/prad/.npm/_logs/2018-02-09T13_37_04_513Z-debug.log
Command npm install failed with exit code 243

`

I've also tried runing this as su to check :
`sudo tns create helloWorld --template https://github.com/NativeScript/template-drawer-navigation-ng
Installing  https://github.com/NativeScript/template-drawer-navigation-ng
Command npm install https://github.com/NativeScript/template-drawer-navigation-ng --silent --save-exact --save failed with exit code 1

`

**Comment by aloketewary** [comment]
If you getting this error, again and again, try removing the **node_modules** directory and then try the 

> npm i --force
command.. using root/administrator privileged.

I think it will install all dependencies and run smooth.
